### ISSUE TITLE
 Please add me as a member

### ISSUE THREAD

**Issue by alirealasad** [YouthHax/youthhax.github.io#14]
thank you

**Comment by Raymo111** [comment]
@alirealasad what do you plan on doing that requires being added to the organization?

**Comment by alirealasad** [comment]
@Raymo111 wait, this not a free to all organization sorry to barge in then &  to answer your question I'll learn a thing or two from different organizations.

**Comment by Raymo111** [comment]
@alirealasad Haha well I'm currently the only member so nothing much for you here
